# Docker compose for development environment
services:
  api:
    image: primeskills-test-api:latest
    env_file:
      - .env
    environment:
      - DB_DSN=root:mypass@tcp(mysql:3306)/primeskills_db?charset=utf8mb4&parseTime=True&loc=Local
    ports:
      - 3000:3000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/ping']
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:lts
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_DATABASE=primeskills_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
